# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "2.68.0"

default_platform :android

platform :android do
  desc 'Build the Android application.'
  private_lane :build do
    gradle(task: 'clean', project_dir: 'android/')
    build_android_app(task: "assembleRelease", project_dir: 'android/')
  end
  
  lane :test do
    increment_version_code(
          gradle_file_path: "project/build.gradle",
          #ext_constant_name: "test"
          #app_folder_name:"app"
    )
  end
  # Fastfile actions accept additional configuration, but
  # don't worry, fastlane will prompt you for required
  # info which you can add here later
  lane :beta do
    # build the release variant
    build
    changelog_from_git_commits(
      pretty: "- (%ae) %s",# Optional, lets you provide a custom format to apply to each commit when generating the changelog text
      date_format: "short",# Optional, lets you provide an additional date format to dates within the pretty-formatted string
      match_lightweight_tag: false,  # Optional, lets you ignore lightweight (non-annotated) tags when searching for the last tag
      merge_commit_filtering: "exclude_merges" # Optional, lets you filter out merge commits
    )
    # upload to Beta by Crashlytics
    crashlytics(
      api_token: "4979341515f04f444d7e6bd68b3ff37943ebb375",
      build_secret: "f15ea7a3eafe2f87bcd0bf83363ffe497878e91c15ec49484db3db2456db5ef0",
      emails: [
        "lucca.aire.dias@ibm.com"
      ]
    )
  end
end
